accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectUpdateView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
    path("<int:pk>/delete/", ProjectDeleteView.as_view(), name="delete_project"),
    path("<int:pk>/edit/", ProjectUpdateView.as_view(), name="update_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import (
    TaskCreateView,
    TaskListView,
    TaskUpdateView,
    TaskDeleteView,
)


urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="delete_task"),

]

tracker/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("tasks/", include("tasks.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
]

projects/models.py
from django.db import models
from django.conf import settings
# from tasks.models import Task


USER_MODEL = settings.AUTH_USER_MODEL


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    urgent = models.BooleanField(default=False)
    archive = models.BooleanField(default=False)
    members = models.ManyToManyField(
        USER_MODEL,
        related_name="projects",
    )

    class Meta:
        ordering = ['archive', '-urgent']

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings


# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):

    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    urgent = models.BooleanField(default=False, null=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL, related_name="tasks", on_delete=models.SET_NULL, null=True
    )

    class Meta:
        ordering = ['-urgent', 'is_completed', 'project']

    def num_complete(self):
        obj = Task.objects.filter(is_completed=True)
        return obj.count()

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.models import User


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()

    context = {"form": form}
    return render(request, "registration/signup.html", context)

projects/views.py
from projects.models import Project
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        user = self.request.user
        return Project.objects.filter(members=user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if (self.request.user.is_authenticated):
            num_complete = []
            for pro in context['project_list']:
                num_complete_section = []
                count = 0
                for j in pro.tasks.values():
                    task_complete = j['is_completed']
                    if task_complete is True:
                        num_complete_section.append(task_complete)
                        count += 1
                if len(num_complete_section) == count:
                    num_complete.append(num_complete_section)
            context['is_complete'] = num_complete
            return context


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"
    fields = ["name", "description"]

    def get_queryset(self):
        user = self.request.user
        return Project.objects.filter(members=user)


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members", "urgent"]

    def get_success_url(self):
        return reverse("show_project", args=[self.object.id])


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    model = Project
    template_name = "projects/delete.html"
    success_url = reverse_lazy('list_projects')


class ProjectUpdateView(LoginRequiredMixin, UpdateView):
    model = Project
    template_name = "projects/edit.html"
    fields = ["name", "description", "members", "urgent", "archive"]

    def get_success_url(self):
        return reverse("show_project", args=[self.object.id])

tasks/views.py
from tasks.models import Task
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee", "urgent"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("show_project", args=[self.object.project.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/mine.html"

    def get_queryset(self):
        user = self.request.user
        return Task.objects.filter(assignee=user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/complete.html"
    fields = ["is_completed", "urgent"]

    def get_success_url(self):
        return reverse("show_my_tasks")


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "tasks/delete.html"

    def get_success_url(self):
        return reverse("show_project", args=[self.object.project.id])

projects/templates/base.html
{% load static %}


<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'show_my_tasks' %}">My tasks</a></li>
        <li><a href="{% url 'list_projects' %}">My projects</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><a href="{% url 'signup' %}">Signup</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}{% endblock content %}
  </main>
</body>

projects/templates/projects/create.html
{% extends 'base.html' %}

{% block content %}

<div class="project-form">
  <h1>Create a new project</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="">
      <button class="">Create</button>
    </div>
  </form>
</div>

{% endblock content %}

projects/templates/projects/delete.html
{% extends 'base.html' %}

{% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete this project?</p>
    {{ form.as_p }}
    <div class="control">
      <button class="button">Delete</button>
    </div>
  </form>
</main>
{% endblock content %}

projects/templates/projects/detail.html
{% extends 'base.html' %} {% load markdownify %}

{% block content %}

<div class="project-detail">
  <h1>{{ project.name }}</h1>
  <p>
    <a href="{% url 'delete_project' project.id %}">Delete Project</a>
    <a href="{% url 'update_project' project.id %}">Update Project</a>
  </p>
  {{ project.description|markdownify }}
  <h2>Tasks</h2>
  <p><a href="{% url 'create_task' %}">Create a new task</a></p>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Assignee</th>
        <th>Start date</th>
        <th>Due date</th>
        <th>Is completed</th>
      </tr>
    </thead>
    <tbody>
      {% for task in project.tasks.all %}
      {% if task.urgent is True and task.is_completed is False %}
      <tr>
        <td style="color:red">{{ task.name }}</td>
        <td style="color:red">{{ task.assignee }}</td>
        <td style="color:red">{{ task.start_date }}</td>
        <td style="color:red">{{ task.due_date }}</td>
        <td style="color:red">{{ task.is_completed | yesno }}</td>
        {% else %}
        <td>{{ task.name }}</td>
        <td>{{ task.assignee }}</td>
        <td>{{ task.start_date }}</td>
        <td>{{ task.due_date }}</td>
        <td>{{ task.is_completed | yesno }}</td>
        {% endif %}
        <td>
          <form method="post" action="{% url 'delete_task' task.id %}">
            {% csrf_token %}
            <input type="hidden" name="deleted">
            <button>Remove task</button>
          </form>
        </td>
      </tr>
      {% empty %}
      <p>This project has no tasks</p>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

projects/templates/projects/edit.html
{% extends 'base.html' %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% load index %}

{% block content %}

<div class="project-list">
  <h1>My Projects</h1>
  <p><a href="{% url 'create_project' %}">Create a new project</a></p>
  {% if project_list|length %}
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Tasks Complete</th>
      </tr>
    </thead>
    <tbody>
      {% for project in project_list %}
      {% if project.urgent is True and project.archive is False %}
      <tr style="color:red">
        <td><a href="{% url 'show_project' project.id %}">
            {{ project.name }}
          </a></td>
        {% else %}
      <tr>
        <td><a href="{% url 'show_project' project.id %}">
            {{ project.name }}
          </a></td>
        {% endif %}
        <td>{{ is_complete | index:forloop.counter0 | length}} of {{ project.tasks.all | length}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>You are not assigned to any projects</p>
  {% endif %}
</div>

{% endblock content %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}

{% block content %}
<div class="task-form">
  <h1>Create a new task</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="">
      <button class="">Create</button>
    </div>
  </form>
</div>
{% endblock content %}

tasks/templates/tasks/mine.html
{% extends 'base.html' %}


{% block content %}

<div class="my-tasks-list">
  <h1>My Tasks</h1>
  {% if task_list|length %}
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>In project</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Is complete</th>
      </tr>
    </thead>
    <tbody>
      {% for task in task_list %}
      {% if task.urgent is True and task.is_completed is False %}
      <tr>
        <td style="color:red">{{ task.name }}</td>
        <td style="color:red"><a href="{% url 'show_project' task.project.id %}">
            {{ task.project }}
          </a></td>
        <td style="color:red">{{ task.start_date }}</td>
        <td style="color:red">{{ task.due_date }}</td>
        {% else %}
        <td>{{ task.name }}</td>
        <td><a href="{% url 'show_project' task.project.id %}">
            {{ task.project }}
          </a></td>
        <td>{{ task.start_date }}</td>
        <td>{{ task.due_date }}</td>
        {% endif %}
        {% if task.is_completed is not True%}
        <td>{{ task.is_completed | yesno:"Done," }}
          <form method="post" action="{% url 'complete_task' task.id %}">
            {% csrf_token %}
            <input type="hidden" name="is_completed" value="True">
            <button>Complete</button>
          </form>
        </td>
        {% else %}
        <td>{{ task.is_completed | yesno:"Done," }}</td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>You have no tasks</p>
  {% endif %}
</div>

{% endblock content %}